#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generador de Gráficas para Plantilla LaTeX - Ingeniería de Software
Genera gráficas de ejemplo relacionadas con DevOps, metodologías ágiles y métricas DORA
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib import rcParams
import os
from matplotlib.patches import FancyBboxPatch, Circle, FancyArrowPatch

# Configuración global para mejorar la calidad de las gráficas
plt.style.use('default')
rcParams['font.family'] = 'serif'
rcParams['font.size'] = 10
rcParams['axes.labelsize'] = 11
rcParams['axes.titlesize'] = 12
rcParams['xtick.labelsize'] = 9
rcParams['ytick.labelsize'] = 9
rcParams['legend.fontsize'] = 9
rcParams['figure.titlesize'] = 13
rcParams['savefig.dpi'] = 300
rcParams['savefig.bbox'] = 'tight'
rcParams['savefig.pad_inches'] = 0.1

# Crear directorio de gráficas si no existe
graphics_dir = 'graphics'
os.makedirs(graphics_dir, exist_ok=True)

# Removed other graph functions to focus on the AI learning collaboration figure only

# Removed generic metrics/DevOps chart generation; focusing only on the AI learning collaboration figure.

# Removed the 'correlation' scatter plot to focus on IA learning figure

def generar_comparacion_metodologias():
    """Remained for possible future use but not used in the default generation flow."""
    
    # Datos para comparación de metodologías
    categorias = ['Flexibilidad', 'Velocidad\nEntrega', 'Calidad\nCódigo', 'Satisfacción\nCliente', 
                  'Gestión\nRiesgos', 'Escalabilidad']
    
    # Puntuaciones (1-10) para cada metodología
    scrum_scores = [8, 9, 7, 9, 6, 7]
    kanban_scores = [9, 7, 8, 8, 8, 8]
    xp_scores = [7, 8, 10, 7, 7, 6]
    
    # Configurar gráfica de radar
    angles = np.linspace(0, 2 * np.pi, len(categorias), endpoint=False).tolist()
    angles += angles[:1]  # Cerrar el círculo
    
    scrum_scores += scrum_scores[:1]
    kanban_scores += kanban_scores[:1]
    xp_scores += xp_scores[:1]
    
    fig, ax = plt.subplots(figsize=(10, 10), subplot_kw=dict(projection='polar'))
    
    # Dibujar las líneas para cada metodología
    ax.plot(angles, scrum_scores, 'o-', linewidth=2, label='Scrum', color='#2E86AB')
    ax.fill(angles, scrum_scores, alpha=0.25, color='#2E86AB')
    
    ax.plot(angles, kanban_scores, 's-', linewidth=2, label='Kanban', color='#F18F01')
    ax.fill(angles, kanban_scores, alpha=0.25, color='#F18F01')
    
    ax.plot(angles, xp_scores, '^-', linewidth=2, label='XP', color='#C73E1D')
    ax.fill(angles, xp_scores, alpha=0.25, color='#C73E1D')
    
    # Configurar etiquetas y límites
    ax.set_xticks(angles[:-1])
    ax.set_xticklabels(categorias)
    ax.set_ylim(0, 10)
    ax.set_yticks(range(0, 11, 2))
    ax.set_yticklabels(range(0, 11, 2))
    ax.grid(True)
    
    plt.title('Comparación de Metodologías Ágiles', size=14, y=1.08)
    plt.legend(loc='upper right', bbox_to_anchor=(1.2, 1.0))
    plt.tight_layout()
    plt.savefig(f'{graphics_dir}/comparacion_metodologias.pdf', format='pdf', bbox_inches='tight')
    plt.savefig(f'{graphics_dir}/comparacion_metodologias.png', format='png', bbox_inches='tight')
    plt.close()
    print("✓ Generada: comparacion_metodologias.pdf/png - (not generated by default)")

def generar_tabla_frameworks():
    """Genera una tabla LaTeX con comparación de frameworks (no generada por defecto)."""
    
    tabla_latex = r"""
\begin{table}[htbp]
\centering
\caption{Comparación de Frameworks de Desarrollo Web}
\label{tab:frameworks}
\begin{tabular}{lccccc}
\toprule
\textbf{Framework} & \textbf{Lenguaje} & \textbf{Performance} & \textbf{Curva Aprendizaje} & \textbf{Comunidad} & \textbf{Puntuación} \\
\midrule
React & JavaScript & Alta & Media & Excelente & 9.2 \\
Angular & TypeScript & Alta & Alta & Excelente & 8.7 \\
Vue.js & JavaScript & Alta & Baja & Buena & 8.9 \\
Django & Python & Media & Media & Excelente & 8.5 \\
Spring Boot & Java & Alta & Alta & Excelente & 8.8 \\
Laravel & PHP & Media & Baja & Buena & 8.1 \\
Express.js & JavaScript & Alta & Baja & Buena & 8.3 \\
\bottomrule
\end{tabular}
\end{table}
"""
    
    # Guardar tabla en archivo
    with open(f'tables/frameworks_comparison.tex', 'w', encoding='utf-8') as f:
        f.write(tabla_latex.strip())
    
    print("✓ Generada: frameworks_comparison.tex")

def generar_uso_ia_aprendizaje_colaborativo():
    """Genera un gráfico que muestra el uso de la IA en el aprendizaje colaborativo en el desarrollo de software"""
    # Categorías de uso: ejemplos tomados de la práctica del equipo
    categorias = ['Resolución de dudas', 'Generación de código', 'Revisión de código',
                  'Explicación de funciones', 'Generación de tests', 'Documentación']
    # Porcentaje de uso (estimado) en equipos que usan IA
    uso_pct = [85, 78, 60, 65, 45, 50]
    # Impacto en aprendizaje (escala 0-10)
    impacto_aprendizaje = [9.0, 8.5, 7.0, 8.0, 6.0, 7.5]

    fig, ax1 = plt.subplots(figsize=(11, 6))

    bar_positions = np.arange(len(categorias))
    bars = ax1.bar(bar_positions, uso_pct, color=['#2E86AB','#A23B72','#F18F01','#C73E1D','#7DCEA0','#5D6D7E'], alpha=0.9)
    ax1.set_ylabel('Porcentaje de uso (%)')
    ax1.set_ylim(0, 100)
    ax1.set_xticks(bar_positions)
    ax1.set_xticklabels(categorias)
    ax1.set_title('Uso de IA en Aprendizaje Colaborativo dentro del Desarrollo de Software')

    # Eje secundario para impacto en aprendizaje (0-10)
    ax2 = ax1.twinx()
    ax2.set_ylabel('Impacto en aprendizaje (0-10)')
    line = ax2.plot(bar_positions, impacto_aprendizaje, color='#111111', marker='o', linewidth=2, label='Impacto')
    ax2.set_ylim(0, 10)

    # Anotar valores de uso e impacto
    for i, bar in enumerate(bars):
        height = bar.get_height()
        ax1.text(bar.get_x() + bar.get_width()/2., height + 1.5, f'{height:.0f}%', ha='center', va='bottom', fontsize=9)
    for i, v in enumerate(impacto_aprendizaje):
        ax2.text(i, v + 0.25, f'{v:.1f}', ha='center', va='bottom', fontsize=9)

    # Leyenda
    handles = [bars[0], line[0]]
    labels = ['Porcentaje de uso', 'Impacto en aprendizaje']
    ax1.legend(handles, labels, loc='upper right')

    plt.tight_layout()
    plt.savefig(f'{graphics_dir}/uso_ia_aprendizaje_colaborativo.pdf', format='pdf')
    plt.savefig(f'{graphics_dir}/uso_ia_aprendizaje_colaborativo.png', format='png')
    plt.close()
    print('✓ Generada: uso_ia_aprendizaje_colaborativo.pdf/png')

def generar_ciclo_desarrollo_ia():
    """Genera un diagrama profesional del ciclo de desarrollo asistido por IA (estilo limpio y moderno)"""
    fig, ax = plt.subplots(figsize=(12, 8))
    ax.axis('off')

    # Coordenadas para las cajas (x, y)
    left_x = -2.2
    right_x = 2.2
    y_positions = [2.2, 1.1, 0, -1.1, -2.2]
    # Cajas izquierda
    left_boxes = [
        (left_x, y_positions[0], 'Elaboración del\nmodelo entidad-relación'),
        (left_x, y_positions[1], 'Ayuda con la sintaxis\ndel código y su\nmantenibilidad'),
        (left_x, y_positions[2], 'Consultas de errores\ny del porqué'),
        (left_x, y_positions[3], 'Explicaciones de funciones\n(Tanto front como back)'),
    ]
    # Cajas derecha
    right_boxes = [
        (right_x, y_positions[0], 'Establecer la arquitectura\ndel proyecto'),
        (right_x, y_positions[1], 'Desarrollo de endpoints'),
        (right_x, y_positions[2], 'Desarrollo de animaciones\nen el front web'),
        (right_x, y_positions[3], 'Conexión del front con el back'),
    ]
    boxes = left_boxes + right_boxes

    # Dibuja las cajas
    box_width = 2.2
    box_height = 0.7
    for x, y, text in boxes:
        bbox = FancyBboxPatch((x - box_width/2, y - box_height/2), box_width, box_height,
                              boxstyle='round,pad=0.04', linewidth=2, edgecolor='#2b6dad', facecolor='#f7fafd', zorder=2)
        ax.add_patch(bbox)
        ax.text(x, y, text, ha='center', va='center', fontsize=13, fontweight='medium', color='#222', zorder=3)

    # Dibuja el círculo central IA
    circle = Circle((0, 0), 1.1, edgecolor='#1f78b4', linewidth=3, facecolor='white', zorder=4)
    ax.add_patch(circle)
    ax.text(0, 0, 'IA', ha='center', va='center', fontsize=32, fontweight='bold', color='#1f78b4', zorder=5)

    # Flechas horizontales (izq-der)
    for i in range(4):
        # De izquierda a derecha
        ax.annotate('', xy=(right_x - box_width/2, y_positions[i]), xytext=(left_x + box_width/2, y_positions[i]),
                    arrowprops=dict(arrowstyle='->', lw=2, color='#2b6dad', shrinkA=10, shrinkB=10), zorder=1)

    # Flechas desde IA a cada caja (líneas suaves, color gris claro)
    for x, y, _ in boxes:
        ax.annotate('', xy=(x, y), xytext=(0, 0),
                    arrowprops=dict(arrowstyle='-|>', lw=1.2, color='#b0b8c1', linestyle='dashed', alpha=0.7, shrinkA=15, shrinkB=15), zorder=0)

    ax.set_xlim(-4, 4)
    ax.set_ylim(-3, 3)
    plt.title('Ciclo de Desarrollo Asistido por IA', fontsize=22, fontweight='bold', pad=24)
    plt.tight_layout()
    plt.savefig(f'{graphics_dir}/ciclo_desarrollo_ia.pdf', format='pdf')
    plt.savefig(f'{graphics_dir}/ciclo_desarrollo_ia.png', format='png')
    plt.close()
    print('✓ Generada: ciclo_desarrollo_ia.pdf/png')

def main():
    """Función principal para generar todas las gráficas"""
    print("🎨 Generando gráficas para plantilla LaTeX...")
    print("=" * 50)
    
    try:
        # Generate the AI learning collaboration figure and the cycle diagram
        # by default we generate the cycle diagram as core figure
        generar_ciclo_desarrollo_ia()
        
        print("=" * 50)
        print("✅ ¡Todas las gráficas y tablas fueron generadas exitosamente!")
        print("\nArchivos generados:")
        print("📊 Gráficas PDF (para LaTeX): graphics/ciclo_desarrollo_ia.pdf")
        print("🖼️  Gráficas PNG (para vista previa): graphics/ciclo_desarrollo_ia.png")
        
    except Exception as e:
        print(f"❌ Error al generar gráficas: {e}")
        raise

if __name__ == "__main__":
    main()