#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generador de Gráficas para Plantilla LaTeX - Ingeniería de Software
Genera gráficas de ejemplo relacionadas con DevOps, metodologías ágiles y métricas DORA
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib import rcParams
import os
from matplotlib.patches import FancyBboxPatch, Circle, FancyArrowPatch

# Configuración global para mejorar la calidad de las gráficas
plt.style.use('default')
rcParams['font.family'] = 'serif'
rcParams['font.size'] = 10
rcParams['axes.labelsize'] = 11
rcParams['axes.titlesize'] = 12
rcParams['xtick.labelsize'] = 9
rcParams['ytick.labelsize'] = 9
rcParams['legend.fontsize'] = 9
rcParams['figure.titlesize'] = 13
rcParams['savefig.dpi'] = 300
rcParams['savefig.bbox'] = 'tight'
rcParams['savefig.pad_inches'] = 0.1

# Crear directorio de gráficas si no existe
graphics_dir = 'graphics'
os.makedirs(graphics_dir, exist_ok=True)

# Removed other graph functions to focus on the AI learning collaboration figure only

# Removed generic metrics/DevOps chart generation; focusing only on the AI learning collaboration figure.

# Removed the 'correlation' scatter plot to focus on IA learning figure

def generar_comparacion_metodologias():
    """Remained for possible future use but not used in the default generation flow."""
    
    # Datos para comparación de metodologías
    categorias = ['Flexibilidad', 'Velocidad\nEntrega', 'Calidad\nCódigo', 'Satisfacción\nCliente', 
                  'Gestión\nRiesgos', 'Escalabilidad']
    
    # Puntuaciones (1-10) para cada metodología
    scrum_scores = [8, 9, 7, 9, 6, 7]
    kanban_scores = [9, 7, 8, 8, 8, 8]
    xp_scores = [7, 8, 10, 7, 7, 6]
    
    # Configurar gráfica de radar
    angles = np.linspace(0, 2 * np.pi, len(categorias), endpoint=False).tolist()
    angles += angles[:1]  # Cerrar el círculo
    
    scrum_scores += scrum_scores[:1]
    kanban_scores += kanban_scores[:1]
    xp_scores += xp_scores[:1]
    
    fig, ax = plt.subplots(figsize=(10, 10), subplot_kw=dict(projection='polar'))
    
    # Dibujar las líneas para cada metodología
    ax.plot(angles, scrum_scores, 'o-', linewidth=2, label='Scrum', color='#2E86AB')
    ax.fill(angles, scrum_scores, alpha=0.25, color='#2E86AB')
    
    ax.plot(angles, kanban_scores, 's-', linewidth=2, label='Kanban', color='#F18F01')
    ax.fill(angles, kanban_scores, alpha=0.25, color='#F18F01')
    
    ax.plot(angles, xp_scores, '^-', linewidth=2, label='XP', color='#C73E1D')
    ax.fill(angles, xp_scores, alpha=0.25, color='#C73E1D')
    
    # Configurar etiquetas y límites
    ax.set_xticks(angles[:-1])
    ax.set_xticklabels(categorias)
    ax.set_ylim(0, 10)
    ax.set_yticks(range(0, 11, 2))
    ax.set_yticklabels(range(0, 11, 2))
    ax.grid(True)
    
    plt.title('Comparación de Metodologías Ágiles', size=14, y=1.08)
    plt.legend(loc='upper right', bbox_to_anchor=(1.2, 1.0))
    plt.tight_layout()
    plt.savefig(f'{graphics_dir}/comparacion_metodologias.pdf', format='pdf', bbox_inches='tight')
    plt.savefig(f'{graphics_dir}/comparacion_metodologias.png', format='png', bbox_inches='tight')
    plt.close()
    print("✓ Generada: comparacion_metodologias.pdf/png - (not generated by default)")

def generar_ciclo_desarrollo_ia():
    """Genera una figura que representa el ciclo de desarrollo asistido por IA"""
    fig, ax = plt.subplots(figsize=(10, 4))
    ax.axis('off')

    # Crear cajas con flechas entre etapas
    steps = ["Recolección\nRequisitos", "Diseño\n(UX/DB)", "Implementación\n(Back/Front)", "Pruebas\n&\nRefactorización", "Despliegue\n&\nMonitoreo", "Feedback\n&\nMejora"]
    x_positions = np.linspace(0.05, 0.95, len(steps))
    y = 0.5
    for i, step in enumerate(steps):
        rect = FancyBboxPatch((x_positions[i]-0.08, y-0.14), 0.16, 0.28,
                              boxstyle='round,pad=0.02', ec='black', fc='#F4F4F4')
        ax.add_patch(rect)
        ax.text(x_positions[i], y, step, ha='center', va='center', fontsize=10)
    # Flechas entre cuadros
    for i in range(len(steps)-1):
        arrow = FancyArrowPatch((x_positions[i]+0.08, y), (x_positions[i+1]-0.08, y),
                                arrowstyle='->', mutation_scale=15, lw=1.5, color='#2E86AB')
        ax.add_patch(arrow)

    plt.title('Ciclo de desarrollo asistido por IA - Autogestión SENA')
    plt.tight_layout()
    plt.savefig(f'{graphics_dir}/ciclo_desarrollo_ia.pdf', format='pdf')
    plt.savefig(f'{graphics_dir}/ciclo_desarrollo_ia.png', format='png')
    plt.close()
    print("✓ Generada: ciclo_desarrollo_ia.pdf/png")

def generar_tabla_frameworks():
    """Genera una tabla LaTeX con comparación de frameworks (no generada por defecto)."""
    
    tabla_latex = r"""
\begin{table}[htbp]
\centering
\caption{Comparación de Frameworks de Desarrollo Web}
\label{tab:frameworks}
\begin{tabular}{lccccc}
\toprule
\textbf{Framework} & \textbf{Lenguaje} & \textbf{Performance} & \textbf{Curva Aprendizaje} & \textbf{Comunidad} & \textbf{Puntuación} \\
\midrule
React & JavaScript & Alta & Media & Excelente & 9.2 \\
Angular & TypeScript & Alta & Alta & Excelente & 8.7 \\
Vue.js & JavaScript & Alta & Baja & Buena & 8.9 \\
Django & Python & Media & Media & Excelente & 8.5 \\
Spring Boot & Java & Alta & Alta & Excelente & 8.8 \\
Laravel & PHP & Media & Baja & Buena & 8.1 \\
Express.js & JavaScript & Alta & Baja & Buena & 8.3 \\
\bottomrule
\end{tabular}
\end{table}
"""
    
    # Guardar tabla en archivo, creando el directorio si no existe
    os.makedirs('tables', exist_ok=True)
    with open(f'tables/frameworks_comparison.tex', 'w', encoding='utf-8') as f:
        f.write(tabla_latex.strip())
    
    print("✓ Generada: frameworks_comparison.tex")

def generar_sprint_timeline():
    """Genera una gráfica tipo Gantt mostrando los sprints y entregables"""
    import matplotlib.dates as mdates
    import datetime as dt
    
    sprints = [
        ("Sprint 1", dt.date(2025, 5, 1), dt.date(2025, 5, 14)),
        ("Sprint 2", dt.date(2025, 5, 15), dt.date(2025, 5, 28)),
        ("Sprint 3", dt.date(2025, 6, 1), dt.date(2025, 6, 14)),
        ("Sprint 4", dt.date(2025, 6, 15), dt.date(2025, 6, 28)),
        ("Sprint 5", dt.date(2025, 7, 1), dt.date(2025, 7, 14)),
        ("Sprint 6", dt.date(2025, 7, 15), dt.date(2025, 7, 28)),
        ("Sprint 7", dt.date(2025, 8, 1), dt.date(2025, 8, 14)),
    ]

    labels = [s[0] for s in sprints]
    starts = [mdates.date2num(s[1]) for s in sprints]
    ends = [mdates.date2num(s[2]) for s in sprints]
    durations = [e - s for s, e in zip(starts, ends)]

    fig, ax = plt.subplots(figsize=(10, 4))
    y_pos = range(len(labels))
    ax.barh(y_pos, durations, left=starts, color='#2E86AB')
    ax.set_yticks(y_pos)
    ax.set_yticklabels(labels)
    ax.xaxis_date()
    ax.set_xlabel('Fecha')
    ax.set_title('Cronograma de Sprints (4 meses, 7 sprints)')
    ax.grid(axis='x', linestyle='--', alpha=0.4)
    plt.tight_layout()
    plt.savefig(f'{graphics_dir}/sprint_timeline.pdf', format='pdf')
    plt.savefig(f'{graphics_dir}/sprint_timeline.png', format='png')
    plt.close()
    print("✓ Generada: sprint_timeline.pdf/png")

def generar_pie_asignacion_tareas():
    """Genera un pie chart con la distribución del tiempo por tipo de tarea"""
    categorias = ['Diseño', 'Implementación', 'Tests', 'Documentación', 'Despliegue', 'Soporte IA']
    valores = [18, 45, 14, 8, 9, 6]  # porcentajes de ejemplo
    colors = ['#2E86AB', '#F18F01', '#A23B72', '#C73E1D', '#7BBF6A', '#A9A9A9']

    fig, ax = plt.subplots(figsize=(8, 6))
    wedges, texts, autotexts = ax.pie(valores, labels=categorias, colors=colors,
                                      autopct='%1.1f%%', startangle=140, textprops={'fontsize': 10})
    ax.axis('equal')
    plt.title('Distribución del esfuerzo por tipo de tarea')
    plt.tight_layout()
    plt.savefig(f'{graphics_dir}/distribucion_tareas.pdf', format='pdf')
    plt.savefig(f'{graphics_dir}/distribucion_tareas.png', format='png')
    plt.close()
    print("✓ Generada: distribucion_tareas.pdf/png")

def generar_ia_usage_bar():
    """Genera un gráfico de barras mostrando la frecuencia de uso de IA por tipo de tarea"""
    tasks = ['Generación Código', 'Explicación de Funciones', 'Diseño UI', 'Pruebas', 'Despliegue']
    counts = [120, 80, 60, 45, 30]  # ejemplo de conteo de prompts/queries

    fig, ax = plt.subplots(figsize=(10, 5))
    bars = ax.bar(tasks, counts, color=['#2E86AB', '#A23B72', '#F18F01', '#C73E1D', '#7BBF6A'])
    ax.set_ylabel('Número de consultas IA')
    ax.set_title('Uso de IA por tipo de tarea')
    for bar in bars:
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 2, f'{int(bar.get_height())}', ha='center')
    plt.tight_layout()
    plt.savefig(f'{graphics_dir}/uso_ia_barras.pdf', format='pdf')
    plt.savefig(f'{graphics_dir}/uso_ia_barras.png', format='png')
    plt.close()
    print("✓ Generada: uso_ia_barras.pdf/png")

def generar_complications_bar():
    """Genera una gráfica mostrando la cantidad de incidencias por categoria de complicación"""
    categorias = ['Integración', 'Entornos', 'IA (falsos positivos)', 'Seguridad', 'UI/UX']
    counts = [18, 12, 9, 6, 7]

    fig, ax = plt.subplots(figsize=(9, 5))
    bars = ax.bar(categorias, counts, color='#C73E1D')
    ax.set_ylabel('Número de incidencias reportadas')
    ax.set_title('Complicaciones reportadas durante el desarrollo')
    for bar in bars:
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.5, f'{int(bar.get_height())}', ha='center')
    plt.tight_layout()
    plt.savefig(f'{graphics_dir}/complicaciones_reportadas.pdf', format='pdf')
    plt.savefig(f'{graphics_dir}/complicaciones_reportadas.png', format='png')
    plt.close()
    print("✓ Generada: complicaciones_reportadas.pdf/png")

def generar_metricas_rendimiento():
    """Genera una gráfica de métricas de rendimiento del sistema"""
    metricas = ['Tiempo Respuesta API', 'Uptime Sistema', 'Satisfacción Usuario', 'Tasa Éxito Asignaciones']
    valores = [0.95, 0.99, 0.92, 0.98]  # valores normalizados 0-1
    colores = ['#2E86AB', '#F18F01', '#A23B72', '#C73E1D']

    fig, ax = plt.subplots(figsize=(10, 6))
    bars = ax.bar(metricas, valores, color=colores)
    ax.set_ylabel('Valor (escala 0-1)')
    ax.set_title('Métricas de Rendimiento del Sistema de Autogestión')
    ax.set_ylim(0, 1)
    for bar in bars:
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.02, f'{bar.get_height():.2f}', ha='center')
    plt.tight_layout()
    plt.savefig(f'{graphics_dir}/metricas_rendimiento.pdf', format='pdf')
    plt.savefig(f'{graphics_dir}/metricas_rendimiento.png', format='png')
    plt.close()
    print("✓ Generada: metricas_rendimiento.pdf/png")

def main():
    """Función principal para generar todas las gráficas"""
    print("🎨 Generando gráficas para plantilla LaTeX...")
    print("=" * 50)
    
    try:
        # Generar figuras disponibles y relevantes
        generar_ciclo_desarrollo_ia()
        generar_comparacion_metodologias()
        generar_tabla_frameworks()
        generar_sprint_timeline()
        generar_pie_asignacion_tareas()
        generar_ia_usage_bar()
        generar_complications_bar()
        generar_metricas_rendimiento()
        
        print("=" * 50)
        print("✅ ¡Todas las gráficas y tablas fueron generadas exitosamente!")
        print("\nArchivos generados:")
        print("📊 Gráficas PDF (para LaTeX): graphics/ciclo_desarrollo_ia.pdf")
        print("🖼️  Gráficas PNG (para vista previa): graphics/ciclo_desarrollo_ia.png")
        
    except Exception as e:
        print(f"❌ Error al generar gráficas: {e}")
        raise

if __name__ == "__main__":
    main()